/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TodayRouteImport } from './routes/today'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as IpoLockupRouteImport } from './routes/ipo-lockup'
import { Route as InsiderRouteImport } from './routes/insider'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksTickerRouteImport } from './routes/stocks.$ticker'
import { Route as BriefingsDateRouteImport } from './routes/briefings.$date'
import { Route as BriefingsWeeksWeekIdRouteImport } from './routes/briefings.weeks.$weekId'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoLockupRoute = IpoLockupRouteImport.update({
  id: '/ipo-lockup',
  path: '/ipo-lockup',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderRoute = InsiderRouteImport.update({
  id: '/insider',
  path: '/insider',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksTickerRoute = StocksTickerRouteImport.update({
  id: '/stocks/$ticker',
  path: '/stocks/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsDateRoute = BriefingsDateRouteImport.update({
  id: '/briefings/$date',
  path: '/briefings/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsWeeksWeekIdRoute = BriefingsWeeksWeekIdRouteImport.update({
  id: '/briefings/weeks/$weekId',
  path: '/briefings/weeks/$weekId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRoute
  '/insider': typeof InsiderRoute
  '/ipo-lockup': typeof IpoLockupRoute
  '/methodology': typeof MethodologyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/replay': typeof ReplayRoute
  '/scanner': typeof ScannerRoute
  '/stock': typeof StockRoute
  '/today': typeof TodayRoute
  '/watchlist': typeof WatchlistRoute
  '/briefings/$date': typeof BriefingsDateRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/briefings/weeks/$weekId': typeof BriefingsWeeksWeekIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRoute
  '/insider': typeof InsiderRoute
  '/ipo-lockup': typeof IpoLockupRoute
  '/methodology': typeof MethodologyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/replay': typeof ReplayRoute
  '/scanner': typeof ScannerRoute
  '/stock': typeof StockRoute
  '/today': typeof TodayRoute
  '/watchlist': typeof WatchlistRoute
  '/briefings/$date': typeof BriefingsDateRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/briefings/weeks/$weekId': typeof BriefingsWeeksWeekIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRoute
  '/insider': typeof InsiderRoute
  '/ipo-lockup': typeof IpoLockupRoute
  '/methodology': typeof MethodologyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/replay': typeof ReplayRoute
  '/scanner': typeof ScannerRoute
  '/stock': typeof StockRoute
  '/today': typeof TodayRoute
  '/watchlist': typeof WatchlistRoute
  '/briefings/$date': typeof BriefingsDateRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/briefings/weeks/$weekId': typeof BriefingsWeeksWeekIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/feedback'
    | '/insider'
    | '/ipo-lockup'
    | '/methodology'
    | '/privacy-policy'
    | '/replay'
    | '/scanner'
    | '/stock'
    | '/today'
    | '/watchlist'
    | '/briefings/$date'
    | '/stocks/$ticker'
    | '/briefings/weeks/$weekId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/feedback'
    | '/insider'
    | '/ipo-lockup'
    | '/methodology'
    | '/privacy-policy'
    | '/replay'
    | '/scanner'
    | '/stock'
    | '/today'
    | '/watchlist'
    | '/briefings/$date'
    | '/stocks/$ticker'
    | '/briefings/weeks/$weekId'
  id:
    | '__root__'
    | '/'
    | '/disclaimer'
    | '/feedback'
    | '/insider'
    | '/ipo-lockup'
    | '/methodology'
    | '/privacy-policy'
    | '/replay'
    | '/scanner'
    | '/stock'
    | '/today'
    | '/watchlist'
    | '/briefings/$date'
    | '/stocks/$ticker'
    | '/briefings/weeks/$weekId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FeedbackRoute: typeof FeedbackRoute
  InsiderRoute: typeof InsiderRoute
  IpoLockupRoute: typeof IpoLockupRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReplayRoute: typeof ReplayRoute
  ScannerRoute: typeof ScannerRoute
  StockRoute: typeof StockRoute
  TodayRoute: typeof TodayRoute
  WatchlistRoute: typeof WatchlistRoute
  BriefingsDateRoute: typeof BriefingsDateRoute
  StocksTickerRoute: typeof StocksTickerRoute
  BriefingsWeeksWeekIdRoute: typeof BriefingsWeeksWeekIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-lockup': {
      id: '/ipo-lockup'
      path: '/ipo-lockup'
      fullPath: '/ipo-lockup'
      preLoaderRoute: typeof IpoLockupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider': {
      id: '/insider'
      path: '/insider'
      fullPath: '/insider'
      preLoaderRoute: typeof InsiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$ticker': {
      id: '/stocks/$ticker'
      path: '/stocks/$ticker'
      fullPath: '/stocks/$ticker'
      preLoaderRoute: typeof StocksTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/$date': {
      id: '/briefings/$date'
      path: '/briefings/$date'
      fullPath: '/briefings/$date'
      preLoaderRoute: typeof BriefingsDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/weeks/$weekId': {
      id: '/briefings/weeks/$weekId'
      path: '/briefings/weeks/$weekId'
      fullPath: '/briefings/weeks/$weekId'
      preLoaderRoute: typeof BriefingsWeeksWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  FeedbackRoute: FeedbackRoute,
  InsiderRoute: InsiderRoute,
  IpoLockupRoute: IpoLockupRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReplayRoute: ReplayRoute,
  ScannerRoute: ScannerRoute,
  StockRoute: StockRoute,
  TodayRoute: TodayRoute,
  WatchlistRoute: WatchlistRoute,
  BriefingsDateRoute: BriefingsDateRoute,
  StocksTickerRoute: StocksTickerRoute,
  BriefingsWeeksWeekIdRoute: BriefingsWeeksWeekIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
