/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as IpoLockupRouteImport } from './routes/ipo-lockup'
import { Route as InsiderRouteImport } from './routes/insider'
import { Route as IndexRouteImport } from './routes/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoLockupRoute = IpoLockupRouteImport.update({
  id: '/ipo-lockup',
  path: '/ipo-lockup',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderRoute = InsiderRouteImport.update({
  id: '/insider',
  path: '/insider',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insider': typeof InsiderRoute
  '/ipo-lockup': typeof IpoLockupRoute
  '/scanner': typeof ScannerRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insider': typeof InsiderRoute
  '/ipo-lockup': typeof IpoLockupRoute
  '/scanner': typeof ScannerRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insider': typeof InsiderRoute
  '/ipo-lockup': typeof IpoLockupRoute
  '/scanner': typeof ScannerRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/insider' | '/ipo-lockup' | '/scanner' | '/today'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/insider' | '/ipo-lockup' | '/scanner' | '/today'
  id: '__root__' | '/' | '/insider' | '/ipo-lockup' | '/scanner' | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsiderRoute: typeof InsiderRoute
  IpoLockupRoute: typeof IpoLockupRoute
  ScannerRoute: typeof ScannerRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo-lockup': {
      id: '/ipo-lockup'
      path: '/ipo-lockup'
      fullPath: '/ipo-lockup'
      preLoaderRoute: typeof IpoLockupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider': {
      id: '/insider'
      path: '/insider'
      fullPath: '/insider'
      preLoaderRoute: typeof InsiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsiderRoute: InsiderRoute,
  IpoLockupRoute: IpoLockupRoute,
  ScannerRoute: ScannerRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
